export const CREATE_NOTE_REQUEST = "CREATE_NOTE_REQUEST";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const CREATE_NOTE_FAIL = "CREATE_NOTE_FAIL";

export const LIST_NOTE_REQUEST = "LIST_NOTE_REQUEST";
export const LIST_NOTE_SUCCESS = "LIST_NOTE_SUCCESS";
export const LIST_NOTE_FAIL = "LIST_NOTE_FAIL";


