export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";

export const USER_RESET_PASS_SUCCESS = "USER_RESET_PASS_SUCCESS";
export const USER_RESET_PASS_REQUEST = "USER_RESET_PASS_REQUEST";
export const USER_RESET_PASS_FAIL = "USER_RESET_PASS_FAIL";

export const USER_FORGOT_PASS_SUCCESS = "USER_FORGOT_PASS_SUCCESS";
export const USER_FORGOT_PASS_REQUEST = "USER_FORGOT_PASS_REQUEST";
export const USER_FORGOT_PASS_FAIL = "USER_FORGOT_PASS_FAIL";

export const USER_REGISTER_OTP = "USER_REGISTER_OTP";
